version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    deploy:
      resources:
        limits:
          cpus: '2'       # Limita o uso de CPU a 2 núcleos
          memory: 2G      # Limita o uso de memória RAM a 2 GB
        reservations:
          cpus: '0.5'     # Reserva 0.5 núcleo de CPU
          memory: 512M    # Reserva 512 MB de memória RAM

volumes:
  mongodb_data: